language: python
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - python-subversion
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/venv-lib"
script:
  - find $HOME/virtualenv/python2.7_with_system_site_packages -name no-global-site-packages.txt -ls
  - python -c 'from svn import core'
jobs:
  include:
    - os: linux
      python: "2.7_with_system_site_packages"
